{{- if (include "docuhost.createConfigMap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "docuhost.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "docuhost.labels" . | nindent 4 }}
data:
  app-url: {{ required "A value for 'app.url' is required." .Values.app.url | quote }}
  db-prefix: {{ required "A value for 'db.prefix' is required." .Values.db.prefix | quote }}
  db-host: {{ required "A value for 'db.host' is required." .Values.db.host | quote }}
  db-port: {{ required "A value for 'db.port' is required." .Values.db.port | quote }}
  db-name: {{ required "A value for 'db.name' is required." .Values.db.name | quote }}
  db-timeout: {{ required "A value for 'db.timeout' is required." .Values.db.timeout | quote }}
  server-port: {{ required "A value for 'server.port' is required." .Values.server.port | quote }}
  server-timeout: {{ required "A value for 'server.timeout' is required." .Values.server.timeout | quote }}
  shortlink-domain: {{ required "A value for 'shortlink.domain' is required." .Values.shortlink.domain | quote }}
  log-debug: {{ .Values.log.debug | default false | quote }}
{{- end }}
